### ISSUE TITLE
Hook doesnt work

### ISSUE THREAD

**Issue by aabilityuk** [ryan-weil/HideProcessHook#3]
Hi hook doesnt work, i tried on Windows 10

**Comment by ryan-weil** [comment]
> Hi hook doesnt work, i tried on Windows 10

Try the latest commit I did to the repository. I have a feeling this will fix your issue.

**Comment by aabilityuk** [comment]
> > Hi hook doesnt work, i tried on Windows 10
> 
> Try the latest commit I did to the repository. I have a feeling this will fix your issue.

thank you for reply, but it doesnt fix the issue

**Comment by ryan-weil** [comment]
> > > Hi hook doesnt work, i tried on Windows 10
> > 
> > 
> > Try the latest commit I did to the repository. I have a feeling this will fix your issue.
> 
> thank you for reply, but it doesnt fix the issue

Well can you explain the actual problem? How is it not working & what are you trying to do? Are you running the test program included? I just tried injecting it to Task Manager on Windows 11 and it works just fine for me.

**Comment by aabilityuk** [comment]
Sure, I compiled both dll and test projects successfully, double checked the path to the dll inside of the test project, but after run the test project nothing happens with explorer.exe 
it is still visible in windows task manager! I think the injection method doesn’t work or something wrong with dll… also I don’t have any antivirus installed and windows guard is disabled

**Comment by ryan-weil** [comment]
> Sure, I compiled both dll and test projects successfully, double checked the path to the dll inside of the test project, but after run the test project nothing happens with explorer.exe it is still visible in windows task manager! I think the injection method doesn’t work or something wrong with dll… also I don’t have any antivirus installed and windows guard is disabled

Ah, that makes sense lol!

So, the purpose of the test project is to load the hook DLL and then call `NtQuerySystemInformation` printing out the results where you can check in the console window if 'explorer.exe' is present. If you want to inject it into Task Manager, you'll have to do that yourself. You can use a program such as Process Hacker to do that. This project does not do any injection, but if you'd like me to add injector code to this repo I'd be able to :) Let me know!

**Comment by aabilityuk** [comment]
> So, the purpose of the test project is to load the hook DLL and then call `NtQuerySystemInformation` printing out the results where you can check in the console window if 'explorer.exe' is present. If you want to inject it into Task Manager, you'll have to do that yourself. You can use a program such as Process Hacker to do that. This project does not do any injection, but if you'd like me to add injector code to this repo I'd be able to :) Let me know!

I dont really understand the purpose :) explorer.exe is present in task manager, i tried inject the Dll with  Process Hacker, but process "explorer.exe" is not hided... Dll doesnt work) Anyway thank you for code sharing

**Comment by ryan-weil** [comment]
> > So, the purpose of the test project is to load the hook DLL and then call `NtQuerySystemInformation` printing out the results where you can check in the console window if 'explorer.exe' is present. If you want to inject it into Task Manager, you'll have to do that yourself. You can use a program such as Process Hacker to do that. This project does not do any injection, but if you'd like me to add injector code to this repo I'd be able to :) Let me know!
> 
> I dont really understand the purpose :) explorer.exe is present in task manager, i tried inject the Dll with Process Hacker, but process "explorer.exe" is not hided... Dll doesnt work) Anyway thank you for code sharing

Do it how I am doing it in the video. If that does not work, try the DLL built in Release mode since is statically linked. For the GIF below, I recorded it on a VM which didn't have MSVC installed so it was required to use the Release mode version (or else it wouldn't load)

![](https://i.imgur.com/odyxKde.gif)

**Comment by ryan-weil** [comment]
I just added an injector project to the repo and updated the README
